package com.pinyougou.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbPayLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_log.out_trade_no
     *
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_log.create_time
     *
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_log.pay_time
     *
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_log.total_fee
     *
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    private Long totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_log.user_id
     *
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_log.transaction_id
     *
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_log.trade_state
     *
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    private String tradeState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_log.order_list
     *
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    private String orderList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay_log.pay_type
     *
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    private String payType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_log.out_trade_no
     *
     * @return the value of tb_pay_log.out_trade_no
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_log.out_trade_no
     *
     * @param outTradeNo the value for tb_pay_log.out_trade_no
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_log.create_time
     *
     * @return the value of tb_pay_log.create_time
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_log.create_time
     *
     * @param createTime the value for tb_pay_log.create_time
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_log.pay_time
     *
     * @return the value of tb_pay_log.pay_time
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_log.pay_time
     *
     * @param payTime the value for tb_pay_log.pay_time
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_log.total_fee
     *
     * @return the value of tb_pay_log.total_fee
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public Long getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_log.total_fee
     *
     * @param totalFee the value for tb_pay_log.total_fee
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public void setTotalFee(Long totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_log.user_id
     *
     * @return the value of tb_pay_log.user_id
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_log.user_id
     *
     * @param userId the value for tb_pay_log.user_id
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_log.transaction_id
     *
     * @return the value of tb_pay_log.transaction_id
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_log.transaction_id
     *
     * @param transactionId the value for tb_pay_log.transaction_id
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_log.trade_state
     *
     * @return the value of tb_pay_log.trade_state
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public String getTradeState() {
        return tradeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_log.trade_state
     *
     * @param tradeState the value for tb_pay_log.trade_state
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public void setTradeState(String tradeState) {
        this.tradeState = tradeState == null ? null : tradeState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_log.order_list
     *
     * @return the value of tb_pay_log.order_list
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public String getOrderList() {
        return orderList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_log.order_list
     *
     * @param orderList the value for tb_pay_log.order_list
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public void setOrderList(String orderList) {
        this.orderList = orderList == null ? null : orderList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay_log.pay_type
     *
     * @return the value of tb_pay_log.pay_type
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay_log.pay_type
     *
     * @param payType the value for tb_pay_log.pay_type
     * @mbg.generated Fri Dec 21 14:34:18 CST 2018
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }
}